# Generated by Django 4.0.2 on 2023-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_product_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
