# Generated by Django 4.0.2 on 2023-01-17 18:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_product_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
