# Generated by Django 4.0.2 on 2023-12-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_product_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
