# Generated by Django 4.0.2 on 2024-01-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_variants_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
