# Generated by Django 4.0.2 on 2024-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_variants_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
