# Generated by Django 4.0.2 on 2022-11-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_product_status'),
        ('cart', '0003_compare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.variants'),
        ),
    ]
