# Generated by Django 4.0.2 on 2022-11-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_product_status'),
        ('cart', '0004_alter_compare_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
