# Generated by Django 4.0.2 on 2022-12-07 17:29

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditNumberCard', models.PositiveIntegerField(default=0)),
                ('date', django_jalali.db.models.jDateTimeField()),
                ('trackingCode', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
