# Generated by Django 4.0.2 on 2022-12-07 17:52

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='creditNumberCard',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='trackingCode',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
