# Generated by Django 4.0.2 on 2022-12-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_checkout_order_alter_checkout_creditnumbercard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
