# Generated by Django 4.0.2 on 2022-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='finalPrice',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
