# Generated by Django 4.0.2 on 2022-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_checkout_finalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
