# Generated by Django 4.0.2 on 2022-12-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='trackingCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
