# Generated by Django 4.0.2 on 2023-01-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_province_city_order_city_order_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='time',
        ),
    ]
