# Generated by Django 4.0.2 on 2023-01-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_checkout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
