# Generated by Django 4.0.2 on 2023-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='trans_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
