# Generated by Django 4.0.2 on 2023-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='creditNumberCard',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
