# Generated by Django 4.0.2 on 2023-12-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_deliveryprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.CharField(max_length=30)),
                ('to_hour', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oo_delivery_hour', to='order.deliveryhour'),
        ),
    ]
