# Generated by Django 4.0.2 on 2023-12-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_deliveryhour_order_delivery_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tipax',
            field=models.BooleanField(default=False),
        ),
    ]
