# Generated by Django 4.0.2 on 2024-10-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_tipax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_paid',
            field=models.BooleanField(default=False),
        ),
    ]
