# Generated by Django 4.0.2 on 2024-10-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_order_cash_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cash_paid',
        ),
    ]
