# Generated by Django 4.0.2 on 2024-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_order_cash_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('online', 'Online Payment')], default='online', max_length=10),
        ),
    ]
