# Generated by Django 4.0.2 on 2024-10-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
