# Generated by Django 4.0.2 on 2024-10-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='online', max_length=10),
        ),
    ]
