# Generated by Django 4.0.2 on 2024-10-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
    ]
