# Generated by Django 4.0.2 on 2024-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
